import { HeaderAction } from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = {
    links: [
      {
        link: "/about",
        label: "Features",
      },
      {
        link: "#1",
        label: "Learn",
        links: [
          {
            link: "/docs",
            label: "Documentation",
          },
          {
            link: "/resources",
            label: "Resources",
          },
          {
            link: "/community",
            label: "Community",
          },
          {
            link: "/blog",
            label: "Blog",
          },
        ],
      },
      {
        link: "/about",
        label: "About",
      },
      {
        link: "/pricing",
        label: "Pricing",
      },
      {
        link: "#2",
        label: "Support",
        links: [
          {
            link: "/faq",
            label: "FAQ",
          },
          {
            link: "/demo",
            label: "Book a demo",
          },
          {
            link: "/forums",
            label: "Forums",
          },
        ],
      },
    ],
  };
  return (
    <html lang="en">
      <body className={"root"}>
        <HeaderAction links={links.links} />
        {children}
      </body>
    </html>
  );
}
